services:
  postgres:
    image: postgres:17-alpine
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
      PGDATA: ${PGDATA}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - retech_meufin_db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - retech-network

networks:
  retech-network:
    driver: bridge

volumes:
  retech_meufin_db_volume:
    name: ${PGVOLUME_NAME}
